#ifndef COMMON_ADAPTER_DEF_H
#define COMMON_ADAPTER_DEF_H

#define UI_RES_FONT_MICROSOFT_YAHEI "Microsoft YaHei"
#define UI_RES_FONT_PINGFANG_SC "PingFang SC"

#ifdef Q_OS_MACOS
#define APP_EXTENSION APP_EXTENSION_MACOS
#define FONT_NAME_DEFAULT UI_RES_FONT_PINGFANG_SC
#define FONT_SIZE_DEFAULT 10

#elif defined Q_OS_WIN
#define APP_EXTENSION APP_EXTENSION_WIN
#define FONT_NAME_DEFAULT UI_RES_FONT_MICROSOFT_YAHEI
#define FONT_SIZE_DEFAULT 12
#else
#define APP_EXTENSION APP_EXTENSION_MACOS
#endif

#endif // COMMON_ADAPTER_DEF_H
